### PR TITLE
CMake: BSD: More feature detection fixes

### PR DESCRIPTION
**Pull request by klemensn**
- fixup! CMake: BSD: Fix bpf detection
- CMake: BSD: Fix <net/if_tun.h> detection
- CMake: BSD: Fix route message detection
- CMake: BSD: Fix sysctl detection
- CMake: BSD: Fix <net/if_arp.h> detection
- CMake: BSD: Fix <net/pfvar.h> detection

### CODE REVIEW

**Comment by xakod** [comment]
@klemensn thank you for cmake support! What do you think about github action for bsd?

**Comment by klemensn** [comment]
> @klemensn thank you for cmake support! What do you think about github action for bsd?

I don't know how GitHub actions work and my suspicion is that BSD support is limited (seems to be the general case with CI systems).

**Comment by xakod** [comment]
> > @klemensn thank you for cmake support! What do you think about github action for bsd?
> 
> I don't know how GitHub actions work and my suspicion is that BSD support is limited (seems to be the general case with CI systems).

Yep, you right. By default, github does not provide any bsd container. But looks like we can use something like this https://github.com/vmactions.

**Comment by klemensn** [comment]
> > > @klemensn thank you for cmake support! What do you think about github action for bsd?
> > 
> > 
> > I don't know how GitHub actions work and my suspicion is that BSD support is limited (seems to be the general case with CI systems).
> 
> Yep, you right. By default, github does not provide any bsd container. But looks like we can use something like this https://github.com/vmactions.

Cool if that works, but as per the link OpenBSD support is already one release behind (we're at 7.3).

**Comment by ofalk** [comment]
Works for me and I'll pull this into devel.
If there is really a why to also test this automagically on BSD, that would be amazing, since I haven't touched a (real) BSD box in (many) years.

**Pull request merged**
