### PR TITLE
CMake, BSD: Fix BPF detection, use clonable device

### PR DESCRIPTION
**Pull request by klemensn**
- CMake: Typofix BSD bpf guard
- BSD: bpf(4) is clonable, use /dev/bpf
- CMake: Fix net/bpf.h detection on OpenBSD
- CMake: BSD: Fix bpf detection
- CMake: Linux: Pick BPF last

### CODE REVIEW

**Comment by klemensn** [comment]
There's more to fix in the CMake code and it makes sense to have it in one PR, so converting it to a draft until I have everything...

**Comment by klemensn** [comment]
This gets `src/eth-bsd.c` to be used instead of `src/eth-none.c` on OpenBSD, as expected.
Linux should still pick `src/eth-linux.c`, but I haven't built there.

`/dev/tun0` detection is equally broken and can use the same fix, but that should be another PR.

**Comment by ofalk** [comment]
Awesome @klemensn - happy someone is looking into the BSD part, because I have none to my avail at the moment !
May I consider this read to be merged?

**Comment by klemensn** [comment]
> Awesome @klemensn - happy someone is looking into the BSD part, because I have none to my avail at the moment ! May I consider this read to be merged?

Your call -- if this looks good enough, I'll fix other CMake stuff as well until OpenBSD is happy enough that I can consider switching upgrading our official `net/libdnet` port/package and switch it over to from GNU auto* tooling.

Works (better) for me, I don't see how this would make it worse for any other system...

**Comment by ofalk** [comment]
> > Awesome @klemensn - happy someone is looking into the BSD part, because I have none to my avail at the moment ! May I consider this read to be merged?
> 
> Your call -- if this looks good enough, I'll fix other CMake stuff as well until OpenBSD is happy enough that I can consider switching upgrading our official `net/libdnet` port/package and switch it over to from GNU auto* tooling.
> 
> Works (better) for me, I don't see how this would make it worse for any other system...

Builds fine on Linux and it looks fine. I'll merge it in a sec - this time as merge commit - not squash it :-)

**Pull request merged**
