### PR TITLE
Fixed cross-compilation support for dnet-config

### PR DESCRIPTION
**Pull request by AlexandreFournier**
Enjoy

### CODE REVIEW

**Comment by sgeto** [comment]
[stolen](https://github.com/sgeto/libdnet) :-D

**Comment by AlexandreFournier** [comment]
At least it's useful for somebody :)

**Comment by sgeto** [comment]
hehe it is! Keep 'em coming!

**Comment by jdefrancesco** [comment]
Anyone here attempt to compile dnet on QNX? I am trying to cross compile nmap for QNX but it seems to fail building at dnet..

**Comment by ofalk** [comment]
This has been pulled in https://github.com/ofalk/libdnet - I'll try to provide the base there for further development, since here nothing is happening any longer.

**Pull request merged**
